version: '3.9'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"

  message-producer:
    build:
      context: ./MessageProducerService
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5000
      - Kafka__BootstrapServers=kafka:9092
      - Kafka__Topic=demo_topic
    depends_on:
      - kafka
      - redis

  message-consumer:
    build:
      context: ./MessageConsumerService
    ports:
      - "5001:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5000
      - Kafka__BootstrapServers=kafka:9092
      - Kafka__Topic=demo_topic
      - Kafka__GroupId=demo_group
      - Redis__ConnectionString=redis:6379
    depends_on:
      - kafka
      - redis
